// flow-typed signature: 699caee4b3f4ff1332314a95aa856167
// flow-typed version: <<STUB>>/@mdx-js/react_v^1.6.18/flow_v0.142.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@mdx-js/react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@mdx-js/react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@mdx-js/react/dist/cjs' {
  declare module.exports: any;
}

declare module '@mdx-js/react/dist/esm' {
  declare module.exports: any;
}

// Filename aliases
declare module '@mdx-js/react/dist/cjs.js' {
  declare module.exports: $Exports<'@mdx-js/react/dist/cjs'>;
}
declare module '@mdx-js/react/dist/esm.js' {
  declare module.exports: $Exports<'@mdx-js/react/dist/esm'>;
}
