// flow-typed signature: 81e8beefdc5218d0c28b4e08d6474939
// flow-typed version: <<STUB>>/framer-motion_v^2.9.1/flow_v0.142.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'framer-motion'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'framer-motion' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'framer-motion/dist/framer-motion.cjs' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/framer-motion.dev' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/framer-motion.es' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/framer-motion' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/minimal-component' {
  declare module.exports: any;
}

// Filename aliases
declare module 'framer-motion/dist/framer-motion.cjs.js' {
  declare module.exports: $Exports<'framer-motion/dist/framer-motion.cjs'>;
}
declare module 'framer-motion/dist/framer-motion.dev.js' {
  declare module.exports: $Exports<'framer-motion/dist/framer-motion.dev'>;
}
declare module 'framer-motion/dist/framer-motion.es.js' {
  declare module.exports: $Exports<'framer-motion/dist/framer-motion.es'>;
}
declare module 'framer-motion/dist/framer-motion.js' {
  declare module.exports: $Exports<'framer-motion/dist/framer-motion'>;
}
declare module 'framer-motion/dist/minimal-component.js' {
  declare module.exports: $Exports<'framer-motion/dist/minimal-component'>;
}
