// flow-typed signature: f2dbfd9a129b7edfdaf218f60e5e0438
// flow-typed version: <<STUB>>/gatsby-plugin-mdx_v^1.2.43/flow_v0.142.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-plugin-mdx'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-plugin-mdx' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-plugin-mdx/__tests__/gatsby-node' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-mdx/component-with-mdx-scope' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-mdx/constants' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-mdx/context' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-mdx/feed' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-mdx/gatsby-browser' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-mdx/gatsby-node' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-mdx/gatsby-ssr' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-mdx/gatsby/create-webpack-config' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-mdx/gatsby/on-create-node' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-mdx/gatsby/on-create-page' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-mdx/gatsby/preprocess-source' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-mdx/gatsby/source-nodes' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-mdx/loaders/mdx-components' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-mdx/loaders/mdx-loader' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-mdx/loaders/mdx-loader.test' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-mdx/loaders/mdx-scopes' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-mdx/loaders/mdx-wrappers' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-mdx/mdx-renderer' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-mdx/mdx-renderer.test' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-mdx/utils/__tests__/fixtures/test-plugin' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-mdx/utils/__tests__/gen-mdx' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-mdx/utils/__tests__/import-parser' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-mdx/utils/babel-plugin-gather-exports' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-mdx/utils/babel-plugin-gather-exports/index.test' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-mdx/utils/babel-plugin-html-attr-to-jsx-attr' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-mdx/utils/babel-plugin-pluck-imports' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-mdx/utils/babel-plugin-pluck-imports/index.test' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-mdx/utils/babel-plugin-remove-export-keywords' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-mdx/utils/babel-plugin-remove-export-keywords/index.test' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-mdx/utils/create-fake-file-node' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-mdx/utils/create-mdx-node' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-mdx/utils/default-options' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-mdx/utils/extract-exports' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-mdx/utils/gen-mdx' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-mdx/utils/get-source-plugins-as-remark-plugins' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-mdx/utils/get-table-of-content' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-mdx/utils/import-parser' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-mdx/utils/interop-default' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-mdx/utils/mdx' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-mdx/utils/render-html' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-mdx/utils/wrap-root-render-html-entry' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-mdx/wrap-root-element' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-plugin-mdx/__tests__/gatsby-node.js' {
  declare module.exports: $Exports<'gatsby-plugin-mdx/__tests__/gatsby-node'>;
}
declare module 'gatsby-plugin-mdx/component-with-mdx-scope.js' {
  declare module.exports: $Exports<'gatsby-plugin-mdx/component-with-mdx-scope'>;
}
declare module 'gatsby-plugin-mdx/constants.js' {
  declare module.exports: $Exports<'gatsby-plugin-mdx/constants'>;
}
declare module 'gatsby-plugin-mdx/context.js' {
  declare module.exports: $Exports<'gatsby-plugin-mdx/context'>;
}
declare module 'gatsby-plugin-mdx/feed.js' {
  declare module.exports: $Exports<'gatsby-plugin-mdx/feed'>;
}
declare module 'gatsby-plugin-mdx/gatsby-browser.js' {
  declare module.exports: $Exports<'gatsby-plugin-mdx/gatsby-browser'>;
}
declare module 'gatsby-plugin-mdx/gatsby-node.js' {
  declare module.exports: $Exports<'gatsby-plugin-mdx/gatsby-node'>;
}
declare module 'gatsby-plugin-mdx/gatsby-ssr.js' {
  declare module.exports: $Exports<'gatsby-plugin-mdx/gatsby-ssr'>;
}
declare module 'gatsby-plugin-mdx/gatsby/create-webpack-config.js' {
  declare module.exports: $Exports<'gatsby-plugin-mdx/gatsby/create-webpack-config'>;
}
declare module 'gatsby-plugin-mdx/gatsby/on-create-node.js' {
  declare module.exports: $Exports<'gatsby-plugin-mdx/gatsby/on-create-node'>;
}
declare module 'gatsby-plugin-mdx/gatsby/on-create-page.js' {
  declare module.exports: $Exports<'gatsby-plugin-mdx/gatsby/on-create-page'>;
}
declare module 'gatsby-plugin-mdx/gatsby/preprocess-source.js' {
  declare module.exports: $Exports<'gatsby-plugin-mdx/gatsby/preprocess-source'>;
}
declare module 'gatsby-plugin-mdx/gatsby/source-nodes.js' {
  declare module.exports: $Exports<'gatsby-plugin-mdx/gatsby/source-nodes'>;
}
declare module 'gatsby-plugin-mdx/index' {
  declare module.exports: $Exports<'gatsby-plugin-mdx'>;
}
declare module 'gatsby-plugin-mdx/index.js' {
  declare module.exports: $Exports<'gatsby-plugin-mdx'>;
}
declare module 'gatsby-plugin-mdx/loaders/mdx-components.js' {
  declare module.exports: $Exports<'gatsby-plugin-mdx/loaders/mdx-components'>;
}
declare module 'gatsby-plugin-mdx/loaders/mdx-loader.js' {
  declare module.exports: $Exports<'gatsby-plugin-mdx/loaders/mdx-loader'>;
}
declare module 'gatsby-plugin-mdx/loaders/mdx-loader.test.js' {
  declare module.exports: $Exports<'gatsby-plugin-mdx/loaders/mdx-loader.test'>;
}
declare module 'gatsby-plugin-mdx/loaders/mdx-scopes.js' {
  declare module.exports: $Exports<'gatsby-plugin-mdx/loaders/mdx-scopes'>;
}
declare module 'gatsby-plugin-mdx/loaders/mdx-wrappers.js' {
  declare module.exports: $Exports<'gatsby-plugin-mdx/loaders/mdx-wrappers'>;
}
declare module 'gatsby-plugin-mdx/mdx-renderer.js' {
  declare module.exports: $Exports<'gatsby-plugin-mdx/mdx-renderer'>;
}
declare module 'gatsby-plugin-mdx/mdx-renderer.test.js' {
  declare module.exports: $Exports<'gatsby-plugin-mdx/mdx-renderer.test'>;
}
declare module 'gatsby-plugin-mdx/utils/__tests__/fixtures/test-plugin.js' {
  declare module.exports: $Exports<'gatsby-plugin-mdx/utils/__tests__/fixtures/test-plugin'>;
}
declare module 'gatsby-plugin-mdx/utils/__tests__/gen-mdx.js' {
  declare module.exports: $Exports<'gatsby-plugin-mdx/utils/__tests__/gen-mdx'>;
}
declare module 'gatsby-plugin-mdx/utils/__tests__/import-parser.js' {
  declare module.exports: $Exports<'gatsby-plugin-mdx/utils/__tests__/import-parser'>;
}
declare module 'gatsby-plugin-mdx/utils/babel-plugin-gather-exports/index' {
  declare module.exports: $Exports<'gatsby-plugin-mdx/utils/babel-plugin-gather-exports'>;
}
declare module 'gatsby-plugin-mdx/utils/babel-plugin-gather-exports/index.js' {
  declare module.exports: $Exports<'gatsby-plugin-mdx/utils/babel-plugin-gather-exports'>;
}
declare module 'gatsby-plugin-mdx/utils/babel-plugin-gather-exports/index.test.js' {
  declare module.exports: $Exports<'gatsby-plugin-mdx/utils/babel-plugin-gather-exports/index.test'>;
}
declare module 'gatsby-plugin-mdx/utils/babel-plugin-html-attr-to-jsx-attr.js' {
  declare module.exports: $Exports<'gatsby-plugin-mdx/utils/babel-plugin-html-attr-to-jsx-attr'>;
}
declare module 'gatsby-plugin-mdx/utils/babel-plugin-pluck-imports/index' {
  declare module.exports: $Exports<'gatsby-plugin-mdx/utils/babel-plugin-pluck-imports'>;
}
declare module 'gatsby-plugin-mdx/utils/babel-plugin-pluck-imports/index.js' {
  declare module.exports: $Exports<'gatsby-plugin-mdx/utils/babel-plugin-pluck-imports'>;
}
declare module 'gatsby-plugin-mdx/utils/babel-plugin-pluck-imports/index.test.js' {
  declare module.exports: $Exports<'gatsby-plugin-mdx/utils/babel-plugin-pluck-imports/index.test'>;
}
declare module 'gatsby-plugin-mdx/utils/babel-plugin-remove-export-keywords/index' {
  declare module.exports: $Exports<'gatsby-plugin-mdx/utils/babel-plugin-remove-export-keywords'>;
}
declare module 'gatsby-plugin-mdx/utils/babel-plugin-remove-export-keywords/index.js' {
  declare module.exports: $Exports<'gatsby-plugin-mdx/utils/babel-plugin-remove-export-keywords'>;
}
declare module 'gatsby-plugin-mdx/utils/babel-plugin-remove-export-keywords/index.test.js' {
  declare module.exports: $Exports<'gatsby-plugin-mdx/utils/babel-plugin-remove-export-keywords/index.test'>;
}
declare module 'gatsby-plugin-mdx/utils/create-fake-file-node.js' {
  declare module.exports: $Exports<'gatsby-plugin-mdx/utils/create-fake-file-node'>;
}
declare module 'gatsby-plugin-mdx/utils/create-mdx-node.js' {
  declare module.exports: $Exports<'gatsby-plugin-mdx/utils/create-mdx-node'>;
}
declare module 'gatsby-plugin-mdx/utils/default-options.js' {
  declare module.exports: $Exports<'gatsby-plugin-mdx/utils/default-options'>;
}
declare module 'gatsby-plugin-mdx/utils/extract-exports.js' {
  declare module.exports: $Exports<'gatsby-plugin-mdx/utils/extract-exports'>;
}
declare module 'gatsby-plugin-mdx/utils/gen-mdx.js' {
  declare module.exports: $Exports<'gatsby-plugin-mdx/utils/gen-mdx'>;
}
declare module 'gatsby-plugin-mdx/utils/get-source-plugins-as-remark-plugins.js' {
  declare module.exports: $Exports<'gatsby-plugin-mdx/utils/get-source-plugins-as-remark-plugins'>;
}
declare module 'gatsby-plugin-mdx/utils/get-table-of-content.js' {
  declare module.exports: $Exports<'gatsby-plugin-mdx/utils/get-table-of-content'>;
}
declare module 'gatsby-plugin-mdx/utils/import-parser.js' {
  declare module.exports: $Exports<'gatsby-plugin-mdx/utils/import-parser'>;
}
declare module 'gatsby-plugin-mdx/utils/interop-default.js' {
  declare module.exports: $Exports<'gatsby-plugin-mdx/utils/interop-default'>;
}
declare module 'gatsby-plugin-mdx/utils/mdx.js' {
  declare module.exports: $Exports<'gatsby-plugin-mdx/utils/mdx'>;
}
declare module 'gatsby-plugin-mdx/utils/render-html.js' {
  declare module.exports: $Exports<'gatsby-plugin-mdx/utils/render-html'>;
}
declare module 'gatsby-plugin-mdx/utils/wrap-root-render-html-entry.js' {
  declare module.exports: $Exports<'gatsby-plugin-mdx/utils/wrap-root-render-html-entry'>;
}
declare module 'gatsby-plugin-mdx/wrap-root-element.js' {
  declare module.exports: $Exports<'gatsby-plugin-mdx/wrap-root-element'>;
}
