// flow-typed signature: 4bbcde58fa525c077db8def8720f19ad
// flow-typed version: <<STUB>>/gatsby-remark-embed-video_v^3.0.10/flow_v0.142.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-remark-embed-video'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-remark-embed-video' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-remark-embed-video/dist/config' {
  declare module.exports: any;
}

declare module 'gatsby-remark-embed-video/dist/EmbedVideo' {
  declare module.exports: any;
}

declare module 'gatsby-remark-embed-video/dist' {
  declare module.exports: any;
}

declare module 'gatsby-remark-embed-video/dist/indexHelpers' {
  declare module.exports: any;
}

declare module 'gatsby-remark-embed-video/dist/indexHelpers.test' {
  declare module.exports: any;
}

declare module 'gatsby-remark-embed-video/dist/videoHelpers/nicovideo' {
  declare module.exports: any;
}

declare module 'gatsby-remark-embed-video/dist/videoHelpers/twitch' {
  declare module.exports: any;
}

declare module 'gatsby-remark-embed-video/dist/videoHelpers/twitch.test' {
  declare module.exports: any;
}

declare module 'gatsby-remark-embed-video/dist/videoHelpers/youtube' {
  declare module.exports: any;
}

declare module 'gatsby-remark-embed-video/dist/videoHelpers/youtube.test' {
  declare module.exports: any;
}

declare module 'gatsby-remark-embed-video/jest.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-remark-embed-video/dist/config.js' {
  declare module.exports: $Exports<'gatsby-remark-embed-video/dist/config'>;
}
declare module 'gatsby-remark-embed-video/dist/EmbedVideo.js' {
  declare module.exports: $Exports<'gatsby-remark-embed-video/dist/EmbedVideo'>;
}
declare module 'gatsby-remark-embed-video/dist/index' {
  declare module.exports: $Exports<'gatsby-remark-embed-video/dist'>;
}
declare module 'gatsby-remark-embed-video/dist/index.js' {
  declare module.exports: $Exports<'gatsby-remark-embed-video/dist'>;
}
declare module 'gatsby-remark-embed-video/dist/indexHelpers.js' {
  declare module.exports: $Exports<'gatsby-remark-embed-video/dist/indexHelpers'>;
}
declare module 'gatsby-remark-embed-video/dist/indexHelpers.test.js' {
  declare module.exports: $Exports<'gatsby-remark-embed-video/dist/indexHelpers.test'>;
}
declare module 'gatsby-remark-embed-video/dist/videoHelpers/nicovideo.js' {
  declare module.exports: $Exports<'gatsby-remark-embed-video/dist/videoHelpers/nicovideo'>;
}
declare module 'gatsby-remark-embed-video/dist/videoHelpers/twitch.js' {
  declare module.exports: $Exports<'gatsby-remark-embed-video/dist/videoHelpers/twitch'>;
}
declare module 'gatsby-remark-embed-video/dist/videoHelpers/twitch.test.js' {
  declare module.exports: $Exports<'gatsby-remark-embed-video/dist/videoHelpers/twitch.test'>;
}
declare module 'gatsby-remark-embed-video/dist/videoHelpers/youtube.js' {
  declare module.exports: $Exports<'gatsby-remark-embed-video/dist/videoHelpers/youtube'>;
}
declare module 'gatsby-remark-embed-video/dist/videoHelpers/youtube.test.js' {
  declare module.exports: $Exports<'gatsby-remark-embed-video/dist/videoHelpers/youtube.test'>;
}
declare module 'gatsby-remark-embed-video/index' {
  declare module.exports: $Exports<'gatsby-remark-embed-video'>;
}
declare module 'gatsby-remark-embed-video/index.js' {
  declare module.exports: $Exports<'gatsby-remark-embed-video'>;
}
declare module 'gatsby-remark-embed-video/jest.config.js' {
  declare module.exports: $Exports<'gatsby-remark-embed-video/jest.config'>;
}
