// flow-typed signature: 20c2f4f4264d1da86dba9143c2156d8d
// flow-typed version: <<STUB>>/gatsby-plugin-client-side-redirect_v^1.1.0/flow_v0.142.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-plugin-client-side-redirect'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-plugin-client-side-redirect' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-plugin-client-side-redirect/clientSideRedirect' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-client-side-redirect/gatsby-node' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-plugin-client-side-redirect/clientSideRedirect.js' {
  declare module.exports: $Exports<'gatsby-plugin-client-side-redirect/clientSideRedirect'>;
}
declare module 'gatsby-plugin-client-side-redirect/gatsby-node.js' {
  declare module.exports: $Exports<'gatsby-plugin-client-side-redirect/gatsby-node'>;
}
declare module 'gatsby-plugin-client-side-redirect/index' {
  declare module.exports: $Exports<'gatsby-plugin-client-side-redirect'>;
}
declare module 'gatsby-plugin-client-side-redirect/index.js' {
  declare module.exports: $Exports<'gatsby-plugin-client-side-redirect'>;
}
