// flow-typed signature: c2416cff8215a15bc691b62e99cfa947
// flow-typed version: <<STUB>>/gatsby-plugin-manifest_v^2.4.32/flow_v0.142.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-plugin-manifest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-plugin-manifest' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-plugin-manifest/common' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-manifest/gatsby-browser' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-manifest/gatsby-node' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-manifest/gatsby-ssr' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-manifest/get-manifest-pathname' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-manifest/safe-sharp' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-plugin-manifest/common.js' {
  declare module.exports: $Exports<'gatsby-plugin-manifest/common'>;
}
declare module 'gatsby-plugin-manifest/gatsby-browser.js' {
  declare module.exports: $Exports<'gatsby-plugin-manifest/gatsby-browser'>;
}
declare module 'gatsby-plugin-manifest/gatsby-node.js' {
  declare module.exports: $Exports<'gatsby-plugin-manifest/gatsby-node'>;
}
declare module 'gatsby-plugin-manifest/gatsby-ssr.js' {
  declare module.exports: $Exports<'gatsby-plugin-manifest/gatsby-ssr'>;
}
declare module 'gatsby-plugin-manifest/get-manifest-pathname.js' {
  declare module.exports: $Exports<'gatsby-plugin-manifest/get-manifest-pathname'>;
}
declare module 'gatsby-plugin-manifest/index' {
  declare module.exports: $Exports<'gatsby-plugin-manifest'>;
}
declare module 'gatsby-plugin-manifest/index.js' {
  declare module.exports: $Exports<'gatsby-plugin-manifest'>;
}
declare module 'gatsby-plugin-manifest/safe-sharp.js' {
  declare module.exports: $Exports<'gatsby-plugin-manifest/safe-sharp'>;
}
