// flow-typed signature: d182a19b4f4895bad34667e90a2ed015
// flow-typed version: <<STUB>>/gatsby-plugin-page-creator_v^2.3.32/flow_v0.142.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-plugin-page-creator'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-plugin-page-creator' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-plugin-page-creator/collection-extract-query-string' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-page-creator/create-client-only-page' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-page-creator/create-page-wrapper' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-page-creator/create-pages-from-collection-builder' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-page-creator/derive-path' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-page-creator/extract-query' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-page-creator/gatsby-node' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-page-creator/get-collection-route-params' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-page-creator/get-match-path' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-page-creator/is-valid-collection-path-implementation' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-page-creator/path-utils' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-page-creator/validate-path-query' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-page-creator/watch-collection-builder' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-plugin-page-creator/collection-extract-query-string.js' {
  declare module.exports: $Exports<'gatsby-plugin-page-creator/collection-extract-query-string'>;
}
declare module 'gatsby-plugin-page-creator/create-client-only-page.js' {
  declare module.exports: $Exports<'gatsby-plugin-page-creator/create-client-only-page'>;
}
declare module 'gatsby-plugin-page-creator/create-page-wrapper.js' {
  declare module.exports: $Exports<'gatsby-plugin-page-creator/create-page-wrapper'>;
}
declare module 'gatsby-plugin-page-creator/create-pages-from-collection-builder.js' {
  declare module.exports: $Exports<'gatsby-plugin-page-creator/create-pages-from-collection-builder'>;
}
declare module 'gatsby-plugin-page-creator/derive-path.js' {
  declare module.exports: $Exports<'gatsby-plugin-page-creator/derive-path'>;
}
declare module 'gatsby-plugin-page-creator/extract-query.js' {
  declare module.exports: $Exports<'gatsby-plugin-page-creator/extract-query'>;
}
declare module 'gatsby-plugin-page-creator/gatsby-node.js' {
  declare module.exports: $Exports<'gatsby-plugin-page-creator/gatsby-node'>;
}
declare module 'gatsby-plugin-page-creator/get-collection-route-params.js' {
  declare module.exports: $Exports<'gatsby-plugin-page-creator/get-collection-route-params'>;
}
declare module 'gatsby-plugin-page-creator/get-match-path.js' {
  declare module.exports: $Exports<'gatsby-plugin-page-creator/get-match-path'>;
}
declare module 'gatsby-plugin-page-creator/index' {
  declare module.exports: $Exports<'gatsby-plugin-page-creator'>;
}
declare module 'gatsby-plugin-page-creator/index.js' {
  declare module.exports: $Exports<'gatsby-plugin-page-creator'>;
}
declare module 'gatsby-plugin-page-creator/is-valid-collection-path-implementation.js' {
  declare module.exports: $Exports<'gatsby-plugin-page-creator/is-valid-collection-path-implementation'>;
}
declare module 'gatsby-plugin-page-creator/path-utils.js' {
  declare module.exports: $Exports<'gatsby-plugin-page-creator/path-utils'>;
}
declare module 'gatsby-plugin-page-creator/validate-path-query.js' {
  declare module.exports: $Exports<'gatsby-plugin-page-creator/validate-path-query'>;
}
declare module 'gatsby-plugin-page-creator/watch-collection-builder.js' {
  declare module.exports: $Exports<'gatsby-plugin-page-creator/watch-collection-builder'>;
}
