// flow-typed signature: 817a5e8599630ddab4ff4cebb7c2f5ca
// flow-typed version: <<STUB>>/gatsby-plugin-lunr_v^1.5.2/flow_v0.142.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-plugin-lunr'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-plugin-lunr' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-plugin-lunr/common' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-lunr/gatsby-browser' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-lunr/gatsby-node' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-plugin-lunr/common.js' {
  declare module.exports: $Exports<'gatsby-plugin-lunr/common'>;
}
declare module 'gatsby-plugin-lunr/gatsby-browser.js' {
  declare module.exports: $Exports<'gatsby-plugin-lunr/gatsby-browser'>;
}
declare module 'gatsby-plugin-lunr/gatsby-node.js' {
  declare module.exports: $Exports<'gatsby-plugin-lunr/gatsby-node'>;
}
declare module 'gatsby-plugin-lunr/index' {
  declare module.exports: $Exports<'gatsby-plugin-lunr'>;
}
declare module 'gatsby-plugin-lunr/index.js' {
  declare module.exports: $Exports<'gatsby-plugin-lunr'>;
}
