// flow-typed signature: c609678e3401834eed47224683475e61
// flow-typed version: <<STUB>>/gatsby-plugin-preload-link-crossorigin_v^1.0.2/flow_v0.142.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-plugin-preload-link-crossorigin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-plugin-preload-link-crossorigin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-plugin-preload-link-crossorigin/gatsby-ssr' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-preload-link-crossorigin/test-projects/base-configuration-test/cypress/integration/crossorigin.spec' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-preload-link-crossorigin/test-projects/base-configuration-test/cypress/plugins' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-preload-link-crossorigin/test-projects/base-configuration-test/cypress/support/commands' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-preload-link-crossorigin/test-projects/base-configuration-test/cypress/support' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-preload-link-crossorigin/test-projects/base-configuration-test/gatsby-browser' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-preload-link-crossorigin/test-projects/base-configuration-test/gatsby-config' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-preload-link-crossorigin/test-projects/base-configuration-test/gatsby-node' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-preload-link-crossorigin/test-projects/base-configuration-test/gatsby-ssr' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-preload-link-crossorigin/test-projects/base-configuration-test/plugins/gatsby-plugin-preload-link-crossorigin/gatsby-ssr' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-preload-link-crossorigin/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-plugin-preload-link-crossorigin/gatsby-ssr.js' {
  declare module.exports: $Exports<'gatsby-plugin-preload-link-crossorigin/gatsby-ssr'>;
}
declare module 'gatsby-plugin-preload-link-crossorigin/index' {
  declare module.exports: $Exports<'gatsby-plugin-preload-link-crossorigin'>;
}
declare module 'gatsby-plugin-preload-link-crossorigin/index.js' {
  declare module.exports: $Exports<'gatsby-plugin-preload-link-crossorigin'>;
}
declare module 'gatsby-plugin-preload-link-crossorigin/test-projects/base-configuration-test/cypress/integration/crossorigin.spec.js' {
  declare module.exports: $Exports<'gatsby-plugin-preload-link-crossorigin/test-projects/base-configuration-test/cypress/integration/crossorigin.spec'>;
}
declare module 'gatsby-plugin-preload-link-crossorigin/test-projects/base-configuration-test/cypress/plugins/index' {
  declare module.exports: $Exports<'gatsby-plugin-preload-link-crossorigin/test-projects/base-configuration-test/cypress/plugins'>;
}
declare module 'gatsby-plugin-preload-link-crossorigin/test-projects/base-configuration-test/cypress/plugins/index.js' {
  declare module.exports: $Exports<'gatsby-plugin-preload-link-crossorigin/test-projects/base-configuration-test/cypress/plugins'>;
}
declare module 'gatsby-plugin-preload-link-crossorigin/test-projects/base-configuration-test/cypress/support/commands.js' {
  declare module.exports: $Exports<'gatsby-plugin-preload-link-crossorigin/test-projects/base-configuration-test/cypress/support/commands'>;
}
declare module 'gatsby-plugin-preload-link-crossorigin/test-projects/base-configuration-test/cypress/support/index' {
  declare module.exports: $Exports<'gatsby-plugin-preload-link-crossorigin/test-projects/base-configuration-test/cypress/support'>;
}
declare module 'gatsby-plugin-preload-link-crossorigin/test-projects/base-configuration-test/cypress/support/index.js' {
  declare module.exports: $Exports<'gatsby-plugin-preload-link-crossorigin/test-projects/base-configuration-test/cypress/support'>;
}
declare module 'gatsby-plugin-preload-link-crossorigin/test-projects/base-configuration-test/gatsby-browser.js' {
  declare module.exports: $Exports<'gatsby-plugin-preload-link-crossorigin/test-projects/base-configuration-test/gatsby-browser'>;
}
declare module 'gatsby-plugin-preload-link-crossorigin/test-projects/base-configuration-test/gatsby-config.js' {
  declare module.exports: $Exports<'gatsby-plugin-preload-link-crossorigin/test-projects/base-configuration-test/gatsby-config'>;
}
declare module 'gatsby-plugin-preload-link-crossorigin/test-projects/base-configuration-test/gatsby-node.js' {
  declare module.exports: $Exports<'gatsby-plugin-preload-link-crossorigin/test-projects/base-configuration-test/gatsby-node'>;
}
declare module 'gatsby-plugin-preload-link-crossorigin/test-projects/base-configuration-test/gatsby-ssr.js' {
  declare module.exports: $Exports<'gatsby-plugin-preload-link-crossorigin/test-projects/base-configuration-test/gatsby-ssr'>;
}
declare module 'gatsby-plugin-preload-link-crossorigin/test-projects/base-configuration-test/plugins/gatsby-plugin-preload-link-crossorigin/gatsby-ssr.js' {
  declare module.exports: $Exports<'gatsby-plugin-preload-link-crossorigin/test-projects/base-configuration-test/plugins/gatsby-plugin-preload-link-crossorigin/gatsby-ssr'>;
}
declare module 'gatsby-plugin-preload-link-crossorigin/utils.js' {
  declare module.exports: $Exports<'gatsby-plugin-preload-link-crossorigin/utils'>;
}
