// flow-typed signature: d9b8a21b89106d68aed6391933c3e425
// flow-typed version: <<STUB>>/gatsby-remark-code-titles_v^1.1.0/flow_v0.142.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-remark-code-titles'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-remark-code-titles' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'gatsby-remark-code-titles/index' {
  declare module.exports: $Exports<'gatsby-remark-code-titles'>;
}
declare module 'gatsby-remark-code-titles/index.js' {
  declare module.exports: $Exports<'gatsby-remark-code-titles'>;
}
