// flow-typed signature: d24c4861880f1e605d0847479a625957
// flow-typed version: <<STUB>>/gatsby-plugin-theme-ui_v^0.3.0/flow_v0.142.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-plugin-theme-ui'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-plugin-theme-ui' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-plugin-theme-ui/gatsby-browser' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-theme-ui/gatsby-ssr' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-theme-ui/src/components' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-theme-ui/src' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-theme-ui/src/provider' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-theme-ui/test/provider' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-plugin-theme-ui/gatsby-browser.js' {
  declare module.exports: $Exports<'gatsby-plugin-theme-ui/gatsby-browser'>;
}
declare module 'gatsby-plugin-theme-ui/gatsby-ssr.js' {
  declare module.exports: $Exports<'gatsby-plugin-theme-ui/gatsby-ssr'>;
}
declare module 'gatsby-plugin-theme-ui/index' {
  declare module.exports: $Exports<'gatsby-plugin-theme-ui'>;
}
declare module 'gatsby-plugin-theme-ui/index.js' {
  declare module.exports: $Exports<'gatsby-plugin-theme-ui'>;
}
declare module 'gatsby-plugin-theme-ui/src/components.js' {
  declare module.exports: $Exports<'gatsby-plugin-theme-ui/src/components'>;
}
declare module 'gatsby-plugin-theme-ui/src/index' {
  declare module.exports: $Exports<'gatsby-plugin-theme-ui/src'>;
}
declare module 'gatsby-plugin-theme-ui/src/index.js' {
  declare module.exports: $Exports<'gatsby-plugin-theme-ui/src'>;
}
declare module 'gatsby-plugin-theme-ui/src/provider.js' {
  declare module.exports: $Exports<'gatsby-plugin-theme-ui/src/provider'>;
}
declare module 'gatsby-plugin-theme-ui/test/provider.js' {
  declare module.exports: $Exports<'gatsby-plugin-theme-ui/test/provider'>;
}
