// flow-typed signature: 7589780175e126dfbe12c4c2d3333fd4
// flow-typed version: <<STUB>>/gatsby-plugin-alias-imports_v^1.0.5/flow_v0.142.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-plugin-alias-imports'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-plugin-alias-imports' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-plugin-alias-imports/gatsby-node' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-plugin-alias-imports/gatsby-node.js' {
  declare module.exports: $Exports<'gatsby-plugin-alias-imports/gatsby-node'>;
}
declare module 'gatsby-plugin-alias-imports/index' {
  declare module.exports: $Exports<'gatsby-plugin-alias-imports'>;
}
declare module 'gatsby-plugin-alias-imports/index.js' {
  declare module.exports: $Exports<'gatsby-plugin-alias-imports'>;
}
