// flow-typed signature: 468368590e6035268b826e1a2c0f626a
// flow-typed version: <<STUB>>/gatsby-plugin-google-analytics_v^2.3.15/flow_v0.142.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-plugin-google-analytics'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-plugin-google-analytics' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-plugin-google-analytics/gatsby-browser' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-google-analytics/gatsby-node' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-google-analytics/gatsby-ssr' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-plugin-google-analytics/gatsby-browser.js' {
  declare module.exports: $Exports<'gatsby-plugin-google-analytics/gatsby-browser'>;
}
declare module 'gatsby-plugin-google-analytics/gatsby-node.js' {
  declare module.exports: $Exports<'gatsby-plugin-google-analytics/gatsby-node'>;
}
declare module 'gatsby-plugin-google-analytics/gatsby-ssr.js' {
  declare module.exports: $Exports<'gatsby-plugin-google-analytics/gatsby-ssr'>;
}
declare module 'gatsby-plugin-google-analytics/index' {
  declare module.exports: $Exports<'gatsby-plugin-google-analytics'>;
}
declare module 'gatsby-plugin-google-analytics/index.js' {
  declare module.exports: $Exports<'gatsby-plugin-google-analytics'>;
}
