// flow-typed signature: 0e1340af72fb2fa362df2762432b14f9
// flow-typed version: <<STUB>>/lunr_v^2.3.9/flow_v0.142.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lunr'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lunr' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'lunr/lib/builder' {
  declare module.exports: any;
}

declare module 'lunr/lib/field_ref' {
  declare module.exports: any;
}

declare module 'lunr/lib/idf' {
  declare module.exports: any;
}

declare module 'lunr/lib' {
  declare module.exports: any;
}

declare module 'lunr/lib/lunr' {
  declare module.exports: any;
}

declare module 'lunr/lib/match_data' {
  declare module.exports: any;
}

declare module 'lunr/lib/pipeline' {
  declare module.exports: any;
}

declare module 'lunr/lib/query_lexer' {
  declare module.exports: any;
}

declare module 'lunr/lib/query_parse_error' {
  declare module.exports: any;
}

declare module 'lunr/lib/query_parser' {
  declare module.exports: any;
}

declare module 'lunr/lib/query' {
  declare module.exports: any;
}

declare module 'lunr/lib/set' {
  declare module.exports: any;
}

declare module 'lunr/lib/stemmer' {
  declare module.exports: any;
}

declare module 'lunr/lib/stop_word_filter' {
  declare module.exports: any;
}

declare module 'lunr/lib/token_set_builder' {
  declare module.exports: any;
}

declare module 'lunr/lib/token_set' {
  declare module.exports: any;
}

declare module 'lunr/lib/token' {
  declare module.exports: any;
}

declare module 'lunr/lib/tokenizer' {
  declare module.exports: any;
}

declare module 'lunr/lib/trimmer' {
  declare module.exports: any;
}

declare module 'lunr/lib/utils' {
  declare module.exports: any;
}

declare module 'lunr/lib/vector' {
  declare module.exports: any;
}

declare module 'lunr/lunr' {
  declare module.exports: any;
}

declare module 'lunr/lunr.min' {
  declare module.exports: any;
}

declare module 'lunr/perf/builder_perf' {
  declare module.exports: any;
}

declare module 'lunr/perf/perf_helper' {
  declare module.exports: any;
}

declare module 'lunr/perf/pipeline_perf' {
  declare module.exports: any;
}

declare module 'lunr/perf/query_parser_perf' {
  declare module.exports: any;
}

declare module 'lunr/perf/search_perf' {
  declare module.exports: any;
}

declare module 'lunr/perf/stemmer_perf' {
  declare module.exports: any;
}

declare module 'lunr/perf/token_set_perf' {
  declare module.exports: any;
}

declare module 'lunr/perf/tokenizer_perf' {
  declare module.exports: any;
}

declare module 'lunr/perf/vector_perf' {
  declare module.exports: any;
}

declare module 'lunr/test/builder_test' {
  declare module.exports: any;
}

declare module 'lunr/test/env/chai' {
  declare module.exports: any;
}

declare module 'lunr/test/env/mocha' {
  declare module.exports: any;
}

declare module 'lunr/test/field_ref_test' {
  declare module.exports: any;
}

declare module 'lunr/test/match_data_test' {
  declare module.exports: any;
}

declare module 'lunr/test/pipeline_test' {
  declare module.exports: any;
}

declare module 'lunr/test/query_lexer_test' {
  declare module.exports: any;
}

declare module 'lunr/test/query_parser_test' {
  declare module.exports: any;
}

declare module 'lunr/test/query_test' {
  declare module.exports: any;
}

declare module 'lunr/test/search_test' {
  declare module.exports: any;
}

declare module 'lunr/test/serialization_test' {
  declare module.exports: any;
}

declare module 'lunr/test/set_test' {
  declare module.exports: any;
}

declare module 'lunr/test/stemmer_test' {
  declare module.exports: any;
}

declare module 'lunr/test/stop_word_filter_test' {
  declare module.exports: any;
}

declare module 'lunr/test/test_helper' {
  declare module.exports: any;
}

declare module 'lunr/test/token_set_test' {
  declare module.exports: any;
}

declare module 'lunr/test/token_test' {
  declare module.exports: any;
}

declare module 'lunr/test/tokenizer_test' {
  declare module.exports: any;
}

declare module 'lunr/test/trimmer_test' {
  declare module.exports: any;
}

declare module 'lunr/test/utils_test' {
  declare module.exports: any;
}

declare module 'lunr/test/vector_test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'lunr/lib/builder.js' {
  declare module.exports: $Exports<'lunr/lib/builder'>;
}
declare module 'lunr/lib/field_ref.js' {
  declare module.exports: $Exports<'lunr/lib/field_ref'>;
}
declare module 'lunr/lib/idf.js' {
  declare module.exports: $Exports<'lunr/lib/idf'>;
}
declare module 'lunr/lib/index' {
  declare module.exports: $Exports<'lunr/lib'>;
}
declare module 'lunr/lib/index.js' {
  declare module.exports: $Exports<'lunr/lib'>;
}
declare module 'lunr/lib/lunr.js' {
  declare module.exports: $Exports<'lunr/lib/lunr'>;
}
declare module 'lunr/lib/match_data.js' {
  declare module.exports: $Exports<'lunr/lib/match_data'>;
}
declare module 'lunr/lib/pipeline.js' {
  declare module.exports: $Exports<'lunr/lib/pipeline'>;
}
declare module 'lunr/lib/query_lexer.js' {
  declare module.exports: $Exports<'lunr/lib/query_lexer'>;
}
declare module 'lunr/lib/query_parse_error.js' {
  declare module.exports: $Exports<'lunr/lib/query_parse_error'>;
}
declare module 'lunr/lib/query_parser.js' {
  declare module.exports: $Exports<'lunr/lib/query_parser'>;
}
declare module 'lunr/lib/query.js' {
  declare module.exports: $Exports<'lunr/lib/query'>;
}
declare module 'lunr/lib/set.js' {
  declare module.exports: $Exports<'lunr/lib/set'>;
}
declare module 'lunr/lib/stemmer.js' {
  declare module.exports: $Exports<'lunr/lib/stemmer'>;
}
declare module 'lunr/lib/stop_word_filter.js' {
  declare module.exports: $Exports<'lunr/lib/stop_word_filter'>;
}
declare module 'lunr/lib/token_set_builder.js' {
  declare module.exports: $Exports<'lunr/lib/token_set_builder'>;
}
declare module 'lunr/lib/token_set.js' {
  declare module.exports: $Exports<'lunr/lib/token_set'>;
}
declare module 'lunr/lib/token.js' {
  declare module.exports: $Exports<'lunr/lib/token'>;
}
declare module 'lunr/lib/tokenizer.js' {
  declare module.exports: $Exports<'lunr/lib/tokenizer'>;
}
declare module 'lunr/lib/trimmer.js' {
  declare module.exports: $Exports<'lunr/lib/trimmer'>;
}
declare module 'lunr/lib/utils.js' {
  declare module.exports: $Exports<'lunr/lib/utils'>;
}
declare module 'lunr/lib/vector.js' {
  declare module.exports: $Exports<'lunr/lib/vector'>;
}
declare module 'lunr/lunr.js' {
  declare module.exports: $Exports<'lunr/lunr'>;
}
declare module 'lunr/lunr.min.js' {
  declare module.exports: $Exports<'lunr/lunr.min'>;
}
declare module 'lunr/perf/builder_perf.js' {
  declare module.exports: $Exports<'lunr/perf/builder_perf'>;
}
declare module 'lunr/perf/perf_helper.js' {
  declare module.exports: $Exports<'lunr/perf/perf_helper'>;
}
declare module 'lunr/perf/pipeline_perf.js' {
  declare module.exports: $Exports<'lunr/perf/pipeline_perf'>;
}
declare module 'lunr/perf/query_parser_perf.js' {
  declare module.exports: $Exports<'lunr/perf/query_parser_perf'>;
}
declare module 'lunr/perf/search_perf.js' {
  declare module.exports: $Exports<'lunr/perf/search_perf'>;
}
declare module 'lunr/perf/stemmer_perf.js' {
  declare module.exports: $Exports<'lunr/perf/stemmer_perf'>;
}
declare module 'lunr/perf/token_set_perf.js' {
  declare module.exports: $Exports<'lunr/perf/token_set_perf'>;
}
declare module 'lunr/perf/tokenizer_perf.js' {
  declare module.exports: $Exports<'lunr/perf/tokenizer_perf'>;
}
declare module 'lunr/perf/vector_perf.js' {
  declare module.exports: $Exports<'lunr/perf/vector_perf'>;
}
declare module 'lunr/test/builder_test.js' {
  declare module.exports: $Exports<'lunr/test/builder_test'>;
}
declare module 'lunr/test/env/chai.js' {
  declare module.exports: $Exports<'lunr/test/env/chai'>;
}
declare module 'lunr/test/env/mocha.js' {
  declare module.exports: $Exports<'lunr/test/env/mocha'>;
}
declare module 'lunr/test/field_ref_test.js' {
  declare module.exports: $Exports<'lunr/test/field_ref_test'>;
}
declare module 'lunr/test/match_data_test.js' {
  declare module.exports: $Exports<'lunr/test/match_data_test'>;
}
declare module 'lunr/test/pipeline_test.js' {
  declare module.exports: $Exports<'lunr/test/pipeline_test'>;
}
declare module 'lunr/test/query_lexer_test.js' {
  declare module.exports: $Exports<'lunr/test/query_lexer_test'>;
}
declare module 'lunr/test/query_parser_test.js' {
  declare module.exports: $Exports<'lunr/test/query_parser_test'>;
}
declare module 'lunr/test/query_test.js' {
  declare module.exports: $Exports<'lunr/test/query_test'>;
}
declare module 'lunr/test/search_test.js' {
  declare module.exports: $Exports<'lunr/test/search_test'>;
}
declare module 'lunr/test/serialization_test.js' {
  declare module.exports: $Exports<'lunr/test/serialization_test'>;
}
declare module 'lunr/test/set_test.js' {
  declare module.exports: $Exports<'lunr/test/set_test'>;
}
declare module 'lunr/test/stemmer_test.js' {
  declare module.exports: $Exports<'lunr/test/stemmer_test'>;
}
declare module 'lunr/test/stop_word_filter_test.js' {
  declare module.exports: $Exports<'lunr/test/stop_word_filter_test'>;
}
declare module 'lunr/test/test_helper.js' {
  declare module.exports: $Exports<'lunr/test/test_helper'>;
}
declare module 'lunr/test/token_set_test.js' {
  declare module.exports: $Exports<'lunr/test/token_set_test'>;
}
declare module 'lunr/test/token_test.js' {
  declare module.exports: $Exports<'lunr/test/token_test'>;
}
declare module 'lunr/test/tokenizer_test.js' {
  declare module.exports: $Exports<'lunr/test/tokenizer_test'>;
}
declare module 'lunr/test/trimmer_test.js' {
  declare module.exports: $Exports<'lunr/test/trimmer_test'>;
}
declare module 'lunr/test/utils_test.js' {
  declare module.exports: $Exports<'lunr/test/utils_test'>;
}
declare module 'lunr/test/vector_test.js' {
  declare module.exports: $Exports<'lunr/test/vector_test'>;
}
