// flow-typed signature: 8b01fa7d440f9b40c9b46154a846702d
// flow-typed version: <<STUB>>/react-sticky-el_v^2.0.5/flow_v0.142.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-sticky-el'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-sticky-el' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-sticky-el/lib/basic-version' {
  declare module.exports: any;
}

declare module 'react-sticky-el/lib/helpers/events' {
  declare module.exports: any;
}

declare module 'react-sticky-el/lib/helpers/find' {
  declare module.exports: any;
}

declare module 'react-sticky-el/lib/helpers/getClosestTransformedParent' {
  declare module.exports: any;
}

declare module 'react-sticky-el/lib/helpers/rect' {
  declare module.exports: any;
}

declare module 'react-sticky-el/lib' {
  declare module.exports: any;
}

declare module 'react-sticky-el/lib/render-props-version' {
  declare module.exports: any;
}

declare module 'react-sticky-el/lib/types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-sticky-el/lib/basic-version.js' {
  declare module.exports: $Exports<'react-sticky-el/lib/basic-version'>;
}
declare module 'react-sticky-el/lib/helpers/events.js' {
  declare module.exports: $Exports<'react-sticky-el/lib/helpers/events'>;
}
declare module 'react-sticky-el/lib/helpers/find.js' {
  declare module.exports: $Exports<'react-sticky-el/lib/helpers/find'>;
}
declare module 'react-sticky-el/lib/helpers/getClosestTransformedParent.js' {
  declare module.exports: $Exports<'react-sticky-el/lib/helpers/getClosestTransformedParent'>;
}
declare module 'react-sticky-el/lib/helpers/rect.js' {
  declare module.exports: $Exports<'react-sticky-el/lib/helpers/rect'>;
}
declare module 'react-sticky-el/lib/index' {
  declare module.exports: $Exports<'react-sticky-el/lib'>;
}
declare module 'react-sticky-el/lib/index.js' {
  declare module.exports: $Exports<'react-sticky-el/lib'>;
}
declare module 'react-sticky-el/lib/render-props-version.js' {
  declare module.exports: $Exports<'react-sticky-el/lib/render-props-version'>;
}
declare module 'react-sticky-el/lib/types.js' {
  declare module.exports: $Exports<'react-sticky-el/lib/types'>;
}
