// flow-typed signature: 02180c1a4961587e489f4035c5b1d61c
// flow-typed version: <<STUB>>/theme-ui_v^0.3.1/flow_v0.142.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'theme-ui'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'theme-ui' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'theme-ui/dist/index.esm' {
  declare module.exports: any;
}

declare module 'theme-ui/dist' {
  declare module.exports: any;
}

declare module 'theme-ui/dist/index.umd' {
  declare module.exports: any;
}

declare module 'theme-ui/src' {
  declare module.exports: any;
}

// Filename aliases
declare module 'theme-ui/dist/index.esm.js' {
  declare module.exports: $Exports<'theme-ui/dist/index.esm'>;
}
declare module 'theme-ui/dist/index' {
  declare module.exports: $Exports<'theme-ui/dist'>;
}
declare module 'theme-ui/dist/index.js' {
  declare module.exports: $Exports<'theme-ui/dist'>;
}
declare module 'theme-ui/dist/index.umd.js' {
  declare module.exports: $Exports<'theme-ui/dist/index.umd'>;
}
declare module 'theme-ui/src/index' {
  declare module.exports: $Exports<'theme-ui/src'>;
}
declare module 'theme-ui/src/index.js' {
  declare module.exports: $Exports<'theme-ui/src'>;
}
