// flow-typed signature: 91387f62e9296dfdf661e8f990780351
// flow-typed version: <<STUB>>/window-or-global_v^1.0.1/flow_v0.142.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'window-or-global'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'window-or-global' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'window-or-global/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module 'window-or-global/lib/index' {
  declare module.exports: $Exports<'window-or-global/lib'>;
}
declare module 'window-or-global/lib/index.js' {
  declare module.exports: $Exports<'window-or-global/lib'>;
}
