---
title: Glossary
order: 4
hideLanguageSelector: true
keywords: "makerdao, glossary, dai, dao"
description: "A glossary of terms used by the Maker Community."
---

# Glossary

## A

#### Approval Voting

- An electoral system that allows people to choose any number of candidates and elects the candidate with the most support.

#### Auction

- A public sale of digital assets to the highest bidder to maintain the stability of the Maker Protocol. The three different types of auctions are Collateral Auctions, Debt Auctions, and Surplus Auctions. An external actor who bids in an auction is called a Keeper.

## B

#### Black Swan

- An unprecedented, unexpected, catastrophic event in which a Collateral asset loses a significant amount of value.

## C

#### `Cat`

- The liquidiations portion of the protocol. This technical term relates to a portion of the "core module" that enables liqudidation of unsafely positioned vaults. 
    - [Documentation](https://docs.makerdao.com/smart-contract-modules/core-module/cat-detailed-documentation)

#### Collateral

- Assets locked in a Vault.

#### Collateral Auction

- A sale of digital assets in where proceeds are used to recover Dai from liquidated Vaults.

#### Collateral Claims

- The amount of redeemable Collateral Dai holders and Vault owners have claim to in the event of an Emergency Shutdown.

#### Collateralization Ratio

- The ratio between a Vault's Collateral and the Dai generated by that Vault.

#### Community Development Improvement Proposal(CDIP)

- A process for submitting and evaluating community-led projects in support of MakerDAO.

#### Continuous Approval Voting

- A process that enables the ongoing election of a single choice from a changing pool of candidates.

#### Core Unit

- The basic building block for organizing work for the DAO. The framework denotes particular long-term objectives that Maker Governance has decided for the protocol to be secure and successful.

## D

#### Dai

- The USD-pegged, decentralized Stablecoin governed by the Maker Protocol.

#### Dai Savings Rate (DSR)

- A variable return earned by holding Dai in the DSR smart-contract.

#### Dai Stablecoin System (DSS)

- Refers to the smart contracts containing the code for Multi-Collateral Dai (MCD).
    - [Documentation](https://github.com/makerdao/dss)

#### Debt Auction

- A sale that recapitalizes the system by auctioning MKR for a fixed amount of Dai. 
    - [Documentation](https://auctions.makerdao.com/flop)

#### Debt Ceiling

- The maximum amount of Dai that can be generated in the Maker Protocol per Collateral type.

#### Decentralized Autonomous Organization (DAO)

- A group of individuals trying to accomplish a common goal using interactions governed by smart contracts.

#### Decentralized Risk Management

- The cooperative interaction between Maker Token Holders and all Risk Teams to manage risks in MakerDAO

#### Development Fund

- The Maker Foundation’s multi-signature wallet used to hold MKR sold for operational expenses.

#### Dilution

- An increase in the amount of MKR in circulation resulting from a Debt Auction.

#### Dust Parameter

- The minimum possible debt of a vault.

#### DsChief

- A smart contract used to let people vote on which smart contract should be used at a given time.
    - [Documentation](https://github.com/makerdao/ds-chief)

#### DssGov

- The Governor Contract, or DssGov for short, is a Dai Stablecoin System Contract that authorises Maker governance to make changes to the Maker protocol by supporting on-chain proposals. This Contract will also support integration with Layer 2 Solutions to enable off-chain vote participation.
    - [Documentation](https://github.com/makerdao/dss-gov)

#### DssGovRewards

- A yield farming program that incentivizes

#### DssSpell

- A smart contract deployed to initiate an Executive Vote. Also known as an "Executive Spell."

## E

#### Emergency Shutdown

- A security feature allowing the system to shut down and make underlying Collateral available for redemption by Vault owners and Dai holders.

#### Executive Vote

- An on-chain election that executes changes to the Maker Protocol using a continuous approval method.

#### Executive Spell

- A smart contract deployed to initiate an Executive Vote. Also referred to as "DssSpell."

## F

#### Facilitator

- The accountable individual(s) responsible for interfacing between Maker Governance and the Contributors, as well as different resources to achieve the Core Objectives of the Protocol. Facilitators are always attached to one or more Core Units and cannot exist in a void.

#### Feed

- An organization or individual that runs a price-feed used in the Maker Protocol's Oracle system.

#### Flap Auction

- A process in which the Maker Protocol sells a fixed amount Dai in the system for MKR that is then burned to reduce its total supply. Also known as a "Surplus Auction."
    -  [Documentation](https://auctions.makerdao.com/flap)

#### Flop Auction

- A sale that recapitalizes the system by auctioning MKR for a fixed amount of Dai.
    - [Documentation](https://auctions.makerdao.com/flop)

## G

#### Gas

- The cost of sending transactions on the Ethereum blockchain; denominated in fractions of Ether (ETH) called gwei.

#### Generated Dai

- The amount of Dai minted against the Collateral deposited in a Maker Vault.

#### Global Debt Ceiling

- The maximum amount of Dai that can be generated using the Maker Protocol.

#### Governance Facilitator

- An elected role responsible for supporting MakerDAO's governance process.

#### Governance Poll

- A time-based vote to gather a soft consensus and measure community sentiment on potential changes to the Maker Protocol.

#### Governance Portal

- A front-end application that allows you to interact with MakerDAO's on-chain governance.

#### Governance Security Module

- A security feature of the Maker Protocol that delays certain governance actions by a predetermined amount of time.

## H

#### Hat

- The 'hat' referrs to a portion of the protocol that ensures an amount of vote, before an executive can be considered "passed."

## I

#### `Ilk`

- The protocols technical term for 'collateral type.' This parameter is used to define a collateral type within the smart contracts of the procotol. 

## J

## K

#### Keepers

- External actors who perform various functions in the Maker Protocol.

#### Keg

- The Keg is a payments streaming system for the protocol. The Keg allows users approved through governance to pay contributors in Dai. 
    - [Documentation](https://github.com/makerdao/keg)

## L

#### Liquidation

- An automated sale of a Vault's Collateral to cover its Generated Dai balance.

#### Liquidation Penalty

- A penalty fee that's applied to a Vault's Generated Dai balance when it is liquidated.

#### Liquidation Price

- Lowest price per unit of Collateral before a Vault is vulnerable to liquidation.

#### Liquidation Ratio

- A risk parameter defining the minimum Collateralization Ratio below which a Vault is vulnerable to liquidation.

## M

#### MakerDAO

- An open-source project on the Ethereum blockchain and a Decentralized Autonomous Organization that governs the Maker Protocol. The project is managed by people around the world who hold the MKR goverance token through Executive Voting and Governance Polling.

#### Maker Foundation

- The organization that was created to develop and bootstrap the Maker Protocol.

#### Maker Improvement Proposal (MIP)

- A framework for submitting and evaluating changes to the Maker Protocol.

#### Maker Protocol

- The system of smart contracts governed by MakerDAO, also known as the Multi-Collateral Dai (MCD) system.

#### Maker Token (MKR)

- The governance token of MakerDAO.

#### Market Maker

- An agent that provides liquidity to a market by offering both bids and asks at a spread for a given asset.

#### Maker Improvement Proposals (MIPs)

- The process by which changes are made to Maker Governance and the Maker Protocol.
    - [Documentation](https://github.com/makerdao/mips)

#### Module

- A smart contract (or collection of smart contracts) that run the protocol for MakerDAO. Examples include; [Oracle Module](https://docs.makerdao.com/smart-contract-modules/oracle-module), [Rates Module](https://docs.makerdao.com/smart-contract-modules/rates-module), [Governance Module](https://docs.makerdao.com/smart-contract-modules/governance-module).

#### Multi-Collateral Dai (MCD)

- The upgraded Maker Protocol that facilitates the use of multiple Collateral types in Vaults.

## N

## O

#### Oracle

- A mechanism that makes off-chain data, such as price data, available on-chain for use in smart-contracts.

#### Oracle Security Module

- A security mechanism that delays and publishes the reference price produced by the Oracle System. A delayed price feed helps vault owners avoid potential liquidations caused by short-term volatility of Collateral assets and allows time to add Collateral in the case of large changes in the value of Collateral assets.

## P

#### Peg

- A fixed exchange rate between two given assets. In the Maker Protocol, Dai maintains a "soft-peg" of 1 Dai to 1 U.S. dollar.

#### Peg Stabilization Module (PSM)

- A system for enforcing Dai's soft-peg to the US Dollar by enabling other dollar-pegged stablecoins to be traded for Dai at a 1:1 ratio.

#### Price-Feed Delay

- A risk parameter that controls the delay of the reference prices published by the Oracle system.

#### Proposal

- A written plan put forward for a vote.

## Q

## R

#### Real-World Assets (RWA)

- A term used when discussing the possibility of on-digital items like real estate and commodities being used as Collateral in the Maker Protocol.

#### Reference Price

- The published price of an asset that is produced by the Maker Protocol's Oracle system and that is used for calculations in the Maker Protocol.

#### Risk Construct

- A collection of data, risk models, outputs, documentation, and analysis.

#### Risk Model

- An analytical model measuring and predicting risk, including the input data and output of the model.

#### Risk Parameters

- A set of configurable, risk-related, variables used to manage the Maker system.

#### Risk Team

- An independent party who creates a Risk Construct and proposes Risk Parameters to MakerDAO Governance.

## S

#### Sai

- A stablecoin similar to Dai that was produced from the Single-Collateral Dai version of the Maker Protocol.

#### Single-Collateral Dai (SCD)

- The previous version of the Maker Protocol, which only accepted Ether (ETH) as Collateral.

#### Smart Contract

- A set of code hosted on a distributed ledger used to execute, manage, or document events.

#### Soft-peg

- Relating the target value of an asset to the absolute value of a fiat currency, allowing for some variance.

#### Stablecoin

- A price-stable cryptocurrency typically pegged to another stable asset or basket of assets. 

#### Stability Fee

- A variable fee charged to a Vault for the generation of Dai, set by MKR holders through the governance of the Maker Protocol.

#### Surplus Auction

- A process in which the Maker Protocol sells a fixed amount Dai in the system for MKR that is then burned to reduce its total supply. Also known as a "Flap Auction."
    - [Documentation](https://auctions.makerdao.com/flap)

## T

#### Time-Based Voting

- A voting design that ends a vote at a predetermined time.

## U

## V

#### `Vat`

- A Smart Contract that contains the core Vault, Dai, and collateral state. The `vat` has no external dependencies and maintains the central "Accounting Invariants" of Dai.
    - [Documentation](https://docs.makerdao.com/smart-contract-modules/core-module/vat-detailed-documentation)

#### Vault

- A core component of the Maker Protocol that facilitates the creation of Dai against locked up Collateral and allows for the destruction of Dai when repaying generated Dai balances.

#### Vote Proxy Contract

- A smart-contract that makes linked wallet voting possible, allowing MKR token holders to vote with their hot wallets by using MKR that is stored on their cold wallets.

#### Voting Contract

- A smart-contract that allows MKR holders to vote with their MKR tokens.

## W

## X

## Y

## Z
 