// flow-typed signature: d495a3ba1c8f4e2aec88ca6b70204768
// flow-typed version: <<STUB>>/@makerdao/dai-ui-icons_v^0.0.62/flow_v0.142.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@makerdao/dai-ui-icons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@makerdao/dai-ui-icons' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@makerdao/dai-ui-icons/dist' {
  declare module.exports: any;
}

declare module '@makerdao/dai-ui-icons/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module '@makerdao/dai-ui-icons/dist/index' {
  declare module.exports: $Exports<'@makerdao/dai-ui-icons/dist'>;
}
declare module '@makerdao/dai-ui-icons/dist/index.js' {
  declare module.exports: $Exports<'@makerdao/dai-ui-icons/dist'>;
}
declare module '@makerdao/dai-ui-icons/lib/index' {
  declare module.exports: $Exports<'@makerdao/dai-ui-icons/lib'>;
}
declare module '@makerdao/dai-ui-icons/lib/index.js' {
  declare module.exports: $Exports<'@makerdao/dai-ui-icons/lib'>;
}
