// flow-typed signature: c9a93b36712dfa4cacbc1deaf28bdb41
// flow-typed version: <<STUB>>/@makerdao/dai-ui-theme-maker_v^0.0.66/flow_v0.142.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@makerdao/dai-ui-theme-maker'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@makerdao/dai-ui-theme-maker' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@makerdao/dai-ui-theme-maker/dist' {
  declare module.exports: any;
}

declare module '@makerdao/dai-ui-theme-maker/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module '@makerdao/dai-ui-theme-maker/dist/index' {
  declare module.exports: $Exports<'@makerdao/dai-ui-theme-maker/dist'>;
}
declare module '@makerdao/dai-ui-theme-maker/dist/index.js' {
  declare module.exports: $Exports<'@makerdao/dai-ui-theme-maker/dist'>;
}
declare module '@makerdao/dai-ui-theme-maker/lib/index' {
  declare module.exports: $Exports<'@makerdao/dai-ui-theme-maker/lib'>;
}
declare module '@makerdao/dai-ui-theme-maker/lib/index.js' {
  declare module.exports: $Exports<'@makerdao/dai-ui-theme-maker/lib'>;
}
