// flow-typed signature: 2babc467b13d14e1a85b0391f81bde1e
// flow-typed version: <<STUB>>/@theme-ui/prism_v^0.3.0/flow_v0.142.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@theme-ui/prism'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@theme-ui/prism' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@theme-ui/prism/babel.config' {
  declare module.exports: any;
}

declare module '@theme-ui/prism/build-presets' {
  declare module.exports: any;
}

declare module '@theme-ui/prism/dist/prism.esm' {
  declare module.exports: any;
}

declare module '@theme-ui/prism/dist/prism' {
  declare module.exports: any;
}

declare module '@theme-ui/prism/dist/prism.umd' {
  declare module.exports: any;
}

declare module '@theme-ui/prism/presets/theme-ui' {
  declare module.exports: any;
}

declare module '@theme-ui/prism/src' {
  declare module.exports: any;
}

declare module '@theme-ui/prism/test' {
  declare module.exports: any;
}

// Filename aliases
declare module '@theme-ui/prism/babel.config.js' {
  declare module.exports: $Exports<'@theme-ui/prism/babel.config'>;
}
declare module '@theme-ui/prism/build-presets.js' {
  declare module.exports: $Exports<'@theme-ui/prism/build-presets'>;
}
declare module '@theme-ui/prism/dist/prism.esm.js' {
  declare module.exports: $Exports<'@theme-ui/prism/dist/prism.esm'>;
}
declare module '@theme-ui/prism/dist/prism.js' {
  declare module.exports: $Exports<'@theme-ui/prism/dist/prism'>;
}
declare module '@theme-ui/prism/dist/prism.umd.js' {
  declare module.exports: $Exports<'@theme-ui/prism/dist/prism.umd'>;
}
declare module '@theme-ui/prism/presets/theme-ui.js' {
  declare module.exports: $Exports<'@theme-ui/prism/presets/theme-ui'>;
}
declare module '@theme-ui/prism/src/index' {
  declare module.exports: $Exports<'@theme-ui/prism/src'>;
}
declare module '@theme-ui/prism/src/index.js' {
  declare module.exports: $Exports<'@theme-ui/prism/src'>;
}
declare module '@theme-ui/prism/test/index' {
  declare module.exports: $Exports<'@theme-ui/prism/test'>;
}
declare module '@theme-ui/prism/test/index.js' {
  declare module.exports: $Exports<'@theme-ui/prism/test'>;
}
