name: IPFS

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Upload to IPFS
      uses: aquiladev/ipfs-action@v0.1.3
      with:
        # Directory path to upload
        path: governance/
        # Level of verbosity
        verbose: true
